name: Maven-version
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-jdk-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache local downloads
      uses: actions/cache@v2
      id: cache
      with:
        path: /root/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven version set
      run: mvn clean versions:set -DnewVersion=0.4.0
    - name: Maven Build
      run: mvn clean package
